repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
        args: ["--config", "pyproject.toml"]
        files: ^(app|tests|alembic)/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args: ["--fix", "--config", "pyproject.toml"]
        files: ^(app|tests|alembic)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        pass_filenames: false
        files: ^(app|tests|alembic)/.*\.py$
        args:
          - --config-file
          - pyproject.toml
          - app
          - tests
          - alembic
        additional_dependencies:
          - fastapi==0.110.0
          - "uvicorn[standard]==0.23.2"
          - pydantic[email]==1.10.12
          - SQLAlchemy==2.0.23
          - alembic==1.13.1
          - celery==5.3.6
          - httpx==0.24.1
          - pytest==7.4.3
          - prometheus-client==0.17.1
          - PyJWT==2.8.0
          - jinja2==3.1.2
          - bleach==6.1.0
          - cachetools==5.3.2
          - cryptography==41.0.7
