apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  labels:
    app: deployment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-service
  template:
    metadata:
      labels:
        app: deployment-service
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/example/deployment-service:latest
          envFrom:
            - secretRef:
                name: deployment-service-env
          command: ["sh", "-c", "alembic upgrade head"]
      containers:
        - name: app
          image: ghcr.io/example/deployment-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: deployment-service-env
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
