apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  labels:
    app: deployment-service
spec:
  type: ClusterIP
  selector:
    app: deployment-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
