name: Lint

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          # Keep cache keys in sync with both dependency manifests.
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install runtime and tooling requirements from the shared manifests.
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run Ruff
        run: ruff check app tests alembic

      - name: Run Black (check)
        run: black --check app tests alembic

      - name: Run mypy
        run: mypy --config-file pyproject.toml app tests alembic
